# Generated by Django 5.1.2 on 2024-11-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_hakkimizda_musteri_say'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hakkimda',
        ),
    ]
